package StockManagement.ObjectModel.ValueObject;
// Generated Aug 10, 2017 10:15:42 AM by Hibernate Tools 4.3.1



/**
 * BranchProduct generated by hbm2java
 */
public class BranchProduct  implements java.io.Serializable {


     private Integer brProductCode;
     private Branch branch;
     private Product product;
     private int qty;

    public BranchProduct() {
    }

    public BranchProduct(Branch branch, Product product, int qty) {
       this.branch = branch;
       this.product = product;
       this.qty = qty;
    }
   
    public Integer getBrProductCode() {
        return this.brProductCode;
    }
    
    public void setBrProductCode(Integer brProductCode) {
        this.brProductCode = brProductCode;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }




}


