package StockManagement.ObjectModel.ValueObject;
// Generated September 26, 2017 11:35:43 PM by Hibernate Tools 4.3.1




/**
 * Menu generated by hbm2java
 */
public class Chart  implements java.io.Serializable {


     private Integer PrCode;
     private String PrName;
     private Integer Orders;
     private float CostPrice;
     private float SellingPrice;

     
    public Chart() {
    }

    public Chart(Integer PrCode, String PrName, Integer Orders, float CostPrice, float SellingPrice) {
        this.PrCode = PrCode;
        this.PrName = PrName;
        this.Orders = Orders;
        this.CostPrice = CostPrice;
        this.SellingPrice = SellingPrice;
    }

    public Integer getPrCode() {
        return PrCode;
    }

    public void setPrCode(Integer PrCode) {
        this.PrCode = PrCode;
    }

    public String getPrName() {
        return PrName;
    }

    public void setPrName(String PrName) {
        this.PrName = PrName;
    }

    public Integer getOrders() {
        return Orders;
    }

    public void setOrders(Integer Orders) {
        this.Orders = Orders;
    }

    public float getCostPrice() {
        return CostPrice;
    }

    public void setCostPrice(float CostPrice) {
        this.CostPrice = CostPrice;
    }

    public float getSellingPrice() {
        return SellingPrice;
    }

    public void setSellingPrice(float SellingPrice) {
        this.SellingPrice = SellingPrice;
    }

    
 


}


