package StockManagement.ObjectModel.ValueObject;
// Generated Sep 27, 2017 9:49:41 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable 
{


     private int invCode;
     private Branch branch;
     private Client client;
     private Product product;
     private TransactionType transactionType;
     private Company company;
     private Date invDate;
     private int invQty;
     private boolean invDbCr;
     private int sellingPrice;
     private int value;
     private Integer discount;

    public Invoice() 
    {
    }

	
    public Invoice(int invCode, Branch branch, Client client, Product product, TransactionType transactionType, Company company, Date invDate, int invQty, boolean invDbCr, int sellingPrice, int value) 
    {
        this.invCode = invCode;
        this.branch = branch;
        this.client = client;
        this.product = product;
        this.transactionType = transactionType;
        this.company = company;
        this.invDate = invDate;
        this.invQty = invQty;
        this.invDbCr = invDbCr;
        this.sellingPrice = sellingPrice;
        this.value = value;
    }
    public Invoice(int invCode, Branch branch, Client client, Product product, TransactionType transactionType, Company company, Date invDate, int invQty, boolean invDbCr, int sellingPrice, int value, Integer discount) 
    {
       this.invCode = invCode;
       this.branch = branch;
       this.client = client;
       this.product = product;
       this.transactionType = transactionType;
       this.company = company;
       this.invDate = invDate;
       this.invQty = invQty;
       this.invDbCr = invDbCr;
       this.sellingPrice = sellingPrice;
       this.value = value;
       this.discount = discount;
    }
   
    public int getInvCode() 
    {
        return this.invCode;
    }
    
    public void setInvCode(int invCode) 
    {
        this.invCode = invCode;
    }
    public Branch getBranch() 
    {
        return this.branch;
    }
    
    public void setBranch(Branch branch) 
    {
        this.branch = branch;
    }
    public Client getClient() 
    {
        return this.client;
    }
    
    public void setClient(Client client) 
    {
        this.client = client;
    }
    public Product getProduct() 
    {
        return this.product;
    }
    
    public void setProduct(Product product) 
    {
        this.product = product;
    }
    public TransactionType getTransactionType() 
    {
        return this.transactionType;
    }
    
    public void setTransactionType(TransactionType transactionType) 
    {
        this.transactionType = transactionType;
    }
    
    public Company getCompany() 
    {
        return this.company;
    }
    
    public void setCompany(Company company) 
    {
        this.company = company;
    }
    
    public Date getInvDate() 
    {
        return this.invDate;
    }
    
    public void setInvDate(Date invDate) 
    {
        this.invDate = invDate;
    }
    
    public int getInvQty() 
    {
        return this.invQty;
    }
    
    public void setInvQty(int invQty) 
    {
        this.invQty = invQty;
    }
    
    public boolean isInvDbCr() 
    {
        return this.invDbCr;
    }
    
    public void setInvDbCr(boolean invDbCr) 
    {
        this.invDbCr = invDbCr;
    }
    
    public int getSellingPrice() 
    {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(int sellingPrice) 
    {
        this.sellingPrice = sellingPrice;
    }
    
    public int getValue() 
    {
        return this.value;
    }
    
    public void setValue(int value) 
    {
        this.value = value;
    }
    
    public Integer getDiscount() 
    {
        return this.discount;
    }
    
    public void setDiscount(Integer discount) 
    {
        this.discount = discount;
    }
}


