package StockManagement.ObjectModel.ValueObject;
// Generated September 26, 2017 11:35:43 PM by Hibernate Tools 4.3.1

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private Integer idMenu;
     private String DisplayName;
     private String Path;
     private boolean IsSecured;

    public Menu() {
    }

    public Menu(String DisplayName, String Path, boolean IsSecured) {
       this.DisplayName = DisplayName;
       this.Path = Path;
       this.IsSecured = IsSecured;
    }

    public Integer getIdMenu() {
        return idMenu;
    }

    public void setIdMenu(Integer idMenu) {
        this.idMenu = idMenu;
    }

    public String getDisplayName() {
        return DisplayName;
    }

    public void setDisplayName(String DisplayName) {
        this.DisplayName = DisplayName;
    }

    public String getPath() {
        return Path;
    }

    public void setPath(String Path) {
        this.Path = Path;
    }

    public boolean isIsSecured() {
        return IsSecured;
    }

    public void setIsSecured(boolean IsSecured) {
        this.IsSecured = IsSecured;
    }
   





}


