package StockManagement.ObjectModel.ValueObject;
// Generated Aug 10, 2017 10:15:42 AM by Hibernate Tools 4.3.1



/**
 * RoleBranch generated by hbm2java
 */
public class RoleBranch  implements java.io.Serializable {


     private Integer roBranchCode;
     private Branch branch;
     private Role role;

    public RoleBranch() {
    }

    public RoleBranch(Branch branch, Role role) {
       this.branch = branch;
       this.role = role;
    }
   
    public Integer getRoBranchCode() {
        return this.roBranchCode;
    }
    
    public void setRoBranchCode(Integer roBranchCode) {
        this.roBranchCode = roBranchCode;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }




}


