package StockManagement.ObjectModel.ValueObject;
// Generated Aug 10, 2017 10:15:42 AM by Hibernate Tools 4.3.1



/**
 * StockProduct generated by hbm2java
 */
public class StockProduct  implements java.io.Serializable {


     private Integer stkProductCode;
     private Product product;
     private Stock stock;
     private int stkPrQty;

    public StockProduct() {
    }

    public StockProduct(Product product, Stock stock, int stkPrQty) {
       this.product = product;
       this.stock = stock;
       this.stkPrQty = stkPrQty;
    }
   
    public Integer getStkProductCode() {
        return this.stkProductCode;
    }
    
    public void setStkProductCode(Integer stkProductCode) {
        this.stkProductCode = stkProductCode;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public int getStkPrQty() {
        return this.stkPrQty;
    }
    
    public void setStkPrQty(int stkPrQty) {
        this.stkPrQty = stkPrQty;
    }




}


